### PR TITLE
Added current version of UCX to task logs

### LINKED ISSUE #539: Add version info when logs are created
Right now the log contain only a basic info message. But we need to know also what version of UCX that was. Add a line that prints this (and maybe other pertinent information, like the current user ID etc.):

```
21:09:32 INFO [databricks.labs.ucx] {MainThread} After job finishes, see debug logs at /Workspace/Users/**redacted**/.ucx/logs/assessment/run-769913644437118/workspace_listing.log
21:09:33 DEBUG [databricks.sdk] {MainThread} /root/.databrickscfg does not exist
21:09:33 DEBUG [databricks.sdk] {MainThread} Attempting to configure auth: pat
21:09:33 DEBUG [databricks.sdk] {MainThread} Attempting to configure auth: basic
21:09:33 DEBUG [databricks.sdk] {MainThread} Attempting to configure auth: metadata-service
...
```

### PR DESCRIPTION
**Pull request by The5cheduler**
Resolves #539

### CODE REVIEW

**Comment by nfx** [comment]
CLA required

**Comment by The5cheduler** [comment]
> CLA required

Not sure how can I sign that.
Contribution file, If you can please show me I can update the Contribution Markdown as well.

**Review by nfx — APPROVED** [review]

**Comment by nfx** [comment]
@The5cheduler please rebase on the latest `main` branch and push again

**Comment by The5cheduler** [comment]
> @The5cheduler please rebase on the latest `main` branch and push again

performed that couple of minutes ago in commit [1e63a8b](https://github.com/databrickslabs/ucx/pull/566/commits/1e63a8b20e673471b17ad8fd488c18929e941b16)

**Pull request merged**
