### PR TITLE
Create dashboards on installation and require `warehouse_id` on installation

### PR DESCRIPTION
**Pull request by nfx**
This PR adds framework to automatically add Redash queries / vizualiations / widgets / dashboards from simple file definitions

### CODE REVIEW

**Review by larsgeorge-db — COMMENTED** [review]
lgtm

**Comment by larsgeorge-db** [comment]
This raises a good point... should the dashboard operate on the summaries the assessment step creates, or on the inventory table(s). I am not for the latter right now as it means implementing the logic to detect things twice, once in the assessment code and then again in the dashboard code. I would rather prefer to have this being created by the assessment step and stored in a report table, then the dashboard simply visualizes the aggregates. Thoughts @nfx @FastLee?

**Comment by nfx** [comment]
Dashboards are created from SQL files
image

**Comment by nfx** [comment]
image
readme notebook gets one more link

**Comment by nfx** [comment]
Assessment report is refreshed after all jobs
image

**Comment by nfx** [comment]
and dashboard is auto-refereshed:
image

**Pull request merged**
