### PR TITLE
Add database location

### PR DESCRIPTION
**Pull request by ericdepaulaf**
### Linked issues

Resolves #..

### Functionality 

- [ ] added relevant user documentation
- [ ] added new CLI command
- [ ] modified existing command: `databricks labs ucx ...`
- [ ] added a new workflow
- [ ] modified existing workflow: `...`
- [ ] added a new table
- [ ] modified existing table: `...`

### Tests

- [ ] manually tested
- [ ] added unit tests
- [ ] added integration tests
- [ ] verified on staging environment (screenshot attached)

### CODE REVIEW

**Comment by ericdepaulaf** [comment]
Add database location

**Review by nfx — CHANGES_REQUESTED** [review]
Thanks for this PR and it makes sense. But make the required change to `lsql` dependent library first.

**Comment by nfx** [comment]
@ericdepaulaf please accept CLA in order for us to be able to merge this PR

**Comment by nfx** [comment]
@ericdepaulaf and run `make fmt`

**Comment by nfx** [comment]
@ericdepaulaf any update?

**Comment by nfx** [comment]
closing due to inactivity

**Pull request closed without merging**
