### PR TITLE
Remove whitespace stripping.

### LINKED ISSUE #253: Clean up and format inline documentation
We currently PyDoc comments to auto generate the example/starter notebook content. We need to improve on the current ChatGPT generated text and find a way to get the text formatted better in the generated markdown.

### PR DESCRIPTION
**Pull request by larsgeorge-db**
Markdown handles multiple whitespaces well anyways, and leaving in the indentation allows for formatting list etc.

Fixes #253

### CODE REVIEW

**Review by nfx — COMMENTED** [review]
Can you attach a screenshot on how it looks like now? It might reinterpret the indent as a block quote

**Comment by tamilselvanveeramani** [comment]
@nfx 

I tested this change, it's good idea to leave the documentation as is for better formatting and readability of README.py

here is how it looks now

image

image

image

**Review by nfx — APPROVED** [review]
Ok, after seeing the screenshot, it looks nicer

**Comment by larsgeorge-db** [comment]
image

image

**Review by nfx — APPROVED** [review]

**Pull request merged**
