### PR TITLE
Feature: Add troubleshooting guide

### PR DESCRIPTION
**Pull request by dmoore247**
## Changes
Add docs/troubleshooting.md file, documenting how to gather logs and resolving a few common errors. This is just the start. This guide was also linked into the main README.md where troubleshooting was mentioned.

### Linked issues

Resolves #..

### Functionality 

- [x] added relevant user documentation
- [ ] added new CLI command
- [ ] modified existing command: `databricks labs ucx ...`
- [ ] added a new workflow
- [ ] modified existing workflow: `...`
- [ ] added a new table
- [ ] modified existing table: `...`

### Tests

- [x] manually tested
- [ ] added unit tests
- [ ] added integration tests
- [ ] verified on staging environment (screenshot attached)

### CODE REVIEW

**Comment by dmoore247** [comment]
Ready for review and merge.

**Comment by dmoore247** [comment]
@dmoore247 Need to align with established TOC conventions for bullets.

**Comment by dmoore247** [comment]
@nfx Good catch on TOC bullet standard, fixed two docs and fixed my defaults. :)

**Review by nfx — COMMENTED** [review]
Let's merge as it is, and improve later

**Pull request merged**
