### PR TITLE
Uses PermissionDenied instead of PermissionError

### LINKED ISSUE #2407: [BUG]: Use Databricks' `PermissionDenied` instead of `PermissionError` when handling Databricks objects
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We sometime use `PermissionError` instead of the Databricks' `PermissionDenied`, examples:

- https://github.com/databrickslabs/ucx/blob/290e841c1562d32942ad70414af6eafdb5808104/src/databricks/labs/ucx/installer/mixins.py#L30
- https://github.com/databrickslabs/ucx/blob/290e841c1562d32942ad70414af6eafdb5808104/src/databricks/labs/ucx/aws/access.py#L345
- https://github.com/databrickslabs/ucx/blob/290e841c1562d32942ad70414af6eafdb5808104/src/databricks/labs/ucx/azure/access.py#L288

### Expected Behavior

Use `PermissionDenied` when handling Databricks resources

### Steps To Reproduce

NA

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by pritishpai**
## Changes
Uses PermissionDenied instead of PermissionError for handling Databricks' object errors

### Linked issues
Resolves #2407 

### Tests
Used existing tests

### CODE REVIEW

**Review by asnare — APPROVED** [review]

**Review by nfx — CHANGES_REQUESTED** [review]
@pritishpai make sure integration test passes

**Review by JCZuurmond — CHANGES_REQUESTED** [review]
Also update the other `PermissionError` in `access.py` as shown in the issue

**Comment by asnare** [comment]
> @pritishpai make sure integration test passes

The failing integration test is also broken on `main` due to the SDK update. I'll make a PR to fix it, similar to #2541.

**Comment by pritishpai** [comment]
Failing integration test test_running_real_remove_backup_groups_job to be resolved when https://github.com/databrickslabs/ucx/pull/2557 is merged.

**Review by JCZuurmond — APPROVED** [review]
lgtm

**Pull request merged**
