### PR TITLE
Added Job Count in the Dashboard

### LINKED ISSUE #826: [FEATURE]: Job total number of jobs and not just the incompatible job count.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Currently the UCX script shows me the number of jobs that are incompatible, but it does not shows the total number of jobs (sometimes we need the total number of jobs and not just the ones that needs DBR version upgrade - because if the code needs to be updated with 3 part naming convention or other changes like hard coded mount points). This is needed for estimating the effort.

### Proposed Solution

At the top of the summary dashboard, please add a the total number of job next to the total number of tables/databases. 

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by prajin-29**
## Changes
Added one more sql for calculating the Total Job Count.

### Linked issues
close: #826 

Resolves #826 

### Functionality 

- [ ] added relevant user documentation
- [ ] added new CLI command
- [ ] modified existing command: `databricks labs ucx ...`
- [ ] added a new workflow
- [ ] modified existing workflow: `...`
- [ ] added a new table
- [ ] modified existing table: `...`

### Tests
Screenshot 2024-02-01 at 12 03 08 PM

- [x] manually tested
- [ ] added unit tests
- [ ] added integration tests
- [ ] verified on staging environment (screenshot attached)

### CODE REVIEW

**Comment by prajin-29** [comment]
@nfx . Should I move the Job Count to the second row and the subsequent dashboard to 1 row down?

**Comment by nfx** [comment]
@prajin-29 whatever makes it look consistent:) provide screenshots

**Comment by nfx** [comment]
@prajin-29 that empty spot looks weird. Can we make something wider?

**Comment by prajin-29** [comment]
> @prajin-29 that empty spot looks weird. Can we make something wider?

@nfx . Updated the dimension.

**Review by nfx — APPROVED** [review]

**Pull request merged**
