### PR TITLE
Include findings on `DENY` grants during assessment

### LINKED ISSUE #1869: [FEATURE]: Report `DENY` ACLs during assessment
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

As noted during #1803, legacy ACLs may contain `DENY` rules interspersed amongst `GRANT` permissions. These are [not supported by UC](https://learn.microsoft.com/en-us/azure/databricks/sql/language-manual/security-deny) and cannot be migrated. As of #1815 these are handled during group migration, but during table migration the ACLs will be dropped and a warning generated.

This may be problematic for customers because it means additional users will end up having permissions on migrated tables, and it's not a 'fail-safe' situation.

Users should be warned earlier than table migration about this being a problem because fixing this might be quite time-consuming.

### Proposed Solution

During assessment we should detect and report on the presence of `DENY` ACLs. 

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by asnare**
## Changes

This PR adds support for flagging DENY permissions on objects, which cannot be migrated to UC.

It also adds some new integration tests for existing grant-scanning.

### Linked issues

Resolves #1869, supersedes #1890.

### Functionality 

- [x] added relevant user documentation
- [ ] added new CLI command
- [ ] modified existing command: `databricks labs ucx ...`
- [ ] added a new workflow
- [X] modified existing workflow: `assessment`
- [ ] added a new table
- [ ] modified existing table: `...`
- [x] modified existing view: `grant_detail`

### Tests

- [x] manually tested
- [ ] added unit tests
- [X] added integration tests
- [x] verified on staging environment (screenshot attached)

### CODE REVIEW

**Comment by asnare** [comment]
Arguably problems with grants should be reported as findings on the target object, which is possible for `catalog`, `schema`, `table`, `view` and `function` permissions but there's no convenient place for reporting on `ANONYMOUS FUNCTION` or `ANY FILE` permissions.

**Review by nfx — APPROVED** [review]
Can you attach a screenshot of a dashboard to verify that layout is not messed up? Looks good from code

**Review by nfx — APPROVED** [review]
lgtm

**Comment by asnare** [comment]
Screenshots of the updated dashboard.
image
image

**Comment by asnare** [comment]
@nfx: screenshots are attached.

Before merging I'd like to add a proper integration test that covers this aspect of the `grant_detail` view, although I can also put that on a new PR.

**Review by nfx — APPROVED** [review]
lgtm

**Pull request merged**
