### PR TITLE
Added `sqlglot` dependency

### PR DESCRIPTION
**Pull request by nfx**
This pull request adds SQLGlot, a SQL parser and reformatter, as a new dependency in the project. It also includes a new test file, `sql_formatter.py`, which contains a test function `test_sql()`. This function reads SQL files from a specified folder and parses each file using SQLGlot. After parsing, it formats the parsed SQL to a more readable version using the `sql()` method from SQLGlot, and then prints out the formatted SQL. The purpose of this test is to ensure that SQL queries can be successfully parsed and formatted by SQLGlot.

In terms of the code changes, the main addition is the inclusion of SQLGlot in the `pyproject.toml` file as a new dependency. Additionally, the `tests/sql_formatter.py` file has been added, which contains a test function that reads SQL files and parses them using SQLGlot. The test function prints out the formatted SQL for each file, which can be used to verify that the SQL queries are being parsed and formatted correctly.

This PR adds `sqlglot` dependency, that would also be required to rewrite views defined in the Hive Metastore to views in UC that follow three-level namespace.

TODO:
- [ ] Add it as dashboard query formatter in `make fmt`
- [ ] Add it as dashboard query linter in `make lint`
- [ ] Fix dashboard framework to understand `/* ... */` comments
- [ ] Pick projected columns from SQL AST instead of defining them in magic comments

### CODE REVIEW

**Comment by zpappa** [comment]
@nfx can you prioritize this one? I need this dependency for my work.

**Comment by nfx** [comment]
@zpappa you can send prs that are decoupled from sqlglot

**Comment by dmoore247** [comment]
I tested this off line, just run `make fmt` and re-push.

**Comment by pohlposition** [comment]
@nfx , do we still need this?

**Comment by nfx** [comment]
Closed in favor of https://github.com/databrickslabs/lsql/pull/66

**Pull request closed without merging**
