### PR TITLE
Added uniqueness in the new warehouse name to avoid name conflict

### LINKED ISSUE #432: Name conflict Error for DBSql Warehouse
When choosing option for creating a new PRO SQL WH - this error is generated -

**databricks.sdk.core.DatabricksError: SQL warehouse with name `Unity Catalog Migration` already exists**

Stack Trace - 
```
QWVFKHF74V:ucx i$ ./install.sh
[i] found Python 3.9.6 -> /usr/bin/python3
[i] found Python 3.9.6 -> /usr/bin/python3
[i] found Python 3.10.5 -> /Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10
[i] found Python 3.10.5 -> /Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10
[i] found Python 3.10.5 -> /Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10
[i] found Python 3.10.5 -> /Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10
[i] found Python 3.11.4 -> /opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/bin/python3.11
[i] found Python 3.11.4 -> /opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/bin/python3.11
[i] latest python is /opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/bin/python3.11
[i] installing venv into: /var/folders/76/zv4jmwyd2djf6c35f2nly9br0000gp/T/tmp.U0fta5tzzx
[+] making sure we have the latest pip version
[+] installing dependencies within ephemeral Virtualenv: /var/folders/76/zv4jmwyd2djf6c35f2nly9br0000gp/T/tmp.U0fta5tzzx
21:46  INFO [_] Installing UCX v0.3.1+3720231010214611
21:46  INFO [_] Please answer a couple of questions to configure Unity Catalog migration
Inventory Database stored in hive_metastore (default: ucx): ucx_dk_2023
Select PRO or SERVERLESS SQL warehouse to run assessment dashboards on
[0] [AUTOMATED] michael_berk's TPCDS Benchmarking Warehouse - 2X-Small, 2 Max Clusters (25090003c0f1610b, SERVERLESS, RUNNING)
[1] [AUTOMATED] michael_berk's TPCDS Benchmarking Warehouse - Small, 2 Max Clusters (e636f18c55f30bbd, SERVERLESS, STOPPED)
[2] [Create new PRO SQL warehouse]
[3] bryanm_test (5188bd989919a524, SERVERLESS, STOPPED)
[4] CnC-powerbi-interface (8cb6692d29bd7657, SERVERLESS, STOPPED)
[5] dbdemos-shared-endpoint (4c770452d7b840f5, SERVERLESS, RUNNING)
[6] EB OneEnv (1deb404990f24995, PRO, STOPPED)
[7] empWarehouse (9fcbfdff745f9130, SERVERLESS, STOPPED)
[8] mla-socgen (b9f3b88d3840ac84, SERVERLESS, STOPPED)
[9] nagyryan-warehouse (383b5da5d22e25e0, SERVERLESS, STOPPED)
[10] nishant (4950dbea3b35de73, SERVERLESS, STOPPED)
[11] Rosa temp (d0b7d1ffb0795594, PRO, RUNNING)
[12] Shared Endpoint (475b94ddc7cd5211, SERVERLESS, RUNNING)
[13] smuralik_sql_warehouse (deac5cd1ec915d64, SERVERLESS, STOPPED)
[14] test1 (0ed6f3024093e5a4, SERVERLESS, STOPPED)
[15] tf-{var.RANDOM} (a3d348b0e556d73c, SERVERLESS, STOPPED)
[16] Unity Catalog Migration (3a61142cd72ba67d, SERVERLESS, STOPPED)
Enter a number between 0 and 16: 2
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/dipankar.kushari/Library/CloudStorage/GoogleDrive-dipankar.kushari@databricks.com/My Drive/10x/UC/UCX/ucx/src/databricks/labs/ucx/install.py", line 714, in <module>
    installer.run()
  File "/Users//Library/CloudStorage/GoogleDrive-dipankar.kushari@databricks.com/My Drive/10x/UC/UCX/ucx/src/databricks/labs/ucx/install.py", line 111, in run
    self._configure()
  File "/Users//Library/CloudStorage/GoogleDrive-@databricks.com/My Drive/10x/UC/UCX/ucx/src/databricks/labs/ucx/install.py", line 272, in _configure
    new_warehouse = self._ws.warehouses.create(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/76/zv4jmwyd2djf6c35f2nly9br0000gp/T/tmp.U0fta5tzzx/lib/python3.11/site-packages/databricks/sdk/service/sql.py", line 3752, in create
    op_response = self._api.do('POST', '/api/2.0/sql/warehouses', body=body, headers=headers)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/76/zv4jmwyd2djf6c35f2nly9br0000gp/T/tmp.U0fta5tzzx/lib/python3.11/site-packages/databricks/sdk/core.py", line 1061, in do
    return retryable(self._perform)(method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/76/zv4jmwyd2djf6c35f2nly9br0000gp/T/tmp.U0fta5tzzx/lib/python3.11/site-packages/databricks/sdk/retries.py", line 47, in wrapper
    raise err
  File "/private/var/folders/76/zv4jmwyd2djf6c35f2nly9br0000gp/T/tmp.U0fta5tzzx/lib/python3.11/site-packages/databricks/sdk/retries.py", line 29, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/76/zv4jmwyd2djf6c35f2nly9br0000gp/T/tmp.U0fta5tzzx/lib/python3.11/site-packages/databricks/sdk/core.py", line 1150, in _perform
    raise self._make_nicer_error(response=response, **payload) from None
databricks.sdk.core.DatabricksError: SQL warehouse with name `Unity Catalog Migration` already exists
```

### PR DESCRIPTION
**Pull request by dipankarkush-db**
Added uniqueness in the new warehouse name to avoid name conflict

Fixes #432

### CODE REVIEW

**Review by nfx — APPROVED** [review]

**Review by dmoore247 — COMMENTED** [review]
Ok

**Comment by dmoore247** [comment]
Ok

**Comment by dipankarkush-db** [comment]
> Ok

Thanks @dmoore247 . Hi @nfx - can we get this merged?

**Comment by dipankarkush-db** [comment]
Hi @nfx - is there any pending or can we merge it

**Comment by nfx** [comment]
https://github.com/databrickslabs/ucx/issues/554

**Review by nfx — APPROVED** [review]

**Pull request merged**
