### PR TITLE
Propagate source location information within the import package dependency graph

### LINKED ISSUE #1418: Propagate file and start/end line/character information for incompatible dependencies
Modify to highlight the exact code range where deprecated import happened

_Originally posted by @nfx in https://github.com/databrickslabs/ucx/pull/1395#discussion_r1566448143_

### PR DESCRIPTION
**Pull request by jimidle**
## Changes

In order to report the location of imports that are either deprecated or will be migrated automatically, the location of the origin source code needs to be preserved. The graph of package dependencies now propagates location information such that reporting can indicate the hierarchy of dependencies that led to discovery of the deprecated import, or one that will be automatically migrated.

### Linked issues

Resolves #1418 

### Functionality 

- [ ] added relevant user documentation
- [ ] added new CLI command
- [ ] modified existing command: `databricks labs ucx ...`
- [ ] added a new workflow
- [ ] modified existing workflow: `...`
- [ ] added a new table
- [ ] modified existing table: `...`
- [x] modifies dependency graph build logic 

### Tests

- [ ] manually tested
- [x] added unit tests
- [ ] added integration tests
- [ ] verified on staging environment (screenshot attached)

### CODE REVIEW

**Comment by ericvergnaud** [comment]
@jimidle, @nfx  this collides significantly with PR #1440

**Comment by jimidle** [comment]
> @jimidle, @nfx this PR collides significantly with PRs #1440 and #1447

I had a feeling it might when I heard what you were working on today. Perhaps it was unwise for us both to work on this. I guess one PR goes in first and the other gets reworked after those changes are in. Did you also solve the infinite visit and loss of dependencies that have a known status? It may be better for me to reapply this after your changes are applied?

**Comment by ericvergnaud** [comment]
in my experience _the infinite visit_ is a side effect of using colliding names in testing i.e. if you name 'path' a sample that imports 'path', then you're in trouble (a python module cannot directly import itself) ?
not sure what you mean by _loss of dependencies that have a known status_ ?
Indeed I suspect it might be better to revisit this after https://github.com/databrickslabs/ucx/pull/1440 and https://github.com/databrickslabs/ucx/pull/1447 are merged (and also maybe #1448)

**Comment by jimidle** [comment]
> in my experience _the infinite visit_ is a side effect of using colliding names in testing i.e. if you name 'path' a sample that imports 'path', then you're in trouble (a python module cannot directly import itself) ? not sure what you mean by _loss of dependencies that have a known status_ ? Indeed I suspect it might be better to revisit this after #1440 and #1447 are merged (and also maybe #1448)

In the current resolver, if it finds that a package is known, it does not return it, so it is not added to the dependency graph. My change returns it, adds it as a dependency, but then does not build its child dependencies.

The infinite walk was caused by the dependencies property adding itself to the list of dependencies. I did not see any code that needed to know about itself other than tests looking for paths. But of course we could have dependencies and child_dependencies as properties, and they can do different things. 

If @nfx wants us to do it in this order then we should bring in your PRs and then I can see what changes you have made and re-apply this PR.

**Review by nfx — APPROVED** [review]
okay for an increment

**Comment by ericvergnaud** [comment]
@nfx the proposal was to do it the other way round
Can you roll this back ?

**Pull request merged**
