### PR TITLE
Fixed logger import path for DEBUG notebook

### LINKED ISSUE #790: Incorrect logger imported for `DEBUG` notebook
`from databricks.labs.ucx.framework import logger` no longer works after `databricks-labs-blueprint` introduction. this is a 2-line code fix

### PR DESCRIPTION
**Pull request by larsgeorge-db**
## Changes

Fixed import in generated DEBUG.py notebook to work with new package layout.

Fixes #790 

### Tests

- [x] manually tested

### CODE REVIEW

**Comment by nfx** [comment]
@larsgeorge-db please attach screenshot for a working fix

**Review by nfx — APPROVED** [review]
please attach a screenshot for a working fix

**Review by nfx — CHANGES_REQUESTED** [review]
please link an issue with `Resolves #` keyword and attach a screenshot of the fix. make PR description a valid markdown.

**Comment by larsgeorge-db** [comment]
Fixed code:

image

**Review by nfx — APPROVED** [review]

**Pull request merged**
